rond-authz/rond

CHANGELOG.md, handler.go, handler_test.go, internal/config/env_test.go, internal/mongoclient/mongoclient_test.go, main_test.go, opaevaluator_test.go, opamiddleware.go, opamiddleware_test.go, openapi_utils.go, openapi_utils_test.go, router_test.go, statusroutes.go, statusroutes_test.go, utilities.go, utilities_test.go
I made the following changes:
- improved tests to use w.Result() to assert the correct response. Without the use of `w.Result()`, it is tested the value set in the ResponseRecorder and not the value returned. For example, the set of the content-type header after the WriteHeader method does not set the header in the response.
- fix response `Content-Type` when an error occurs: move set of header before the WriteHeader
- remove unnecessary service logs when tests run
=> fix content type in response error

.github/dependabot.yml, .github/workflows/test.yml
Old versions depend on Node 12 which has been deprecated
=> update: github actions versions

.github/release.yml, .github/workflows/release.yml, CHANGELOG.md
I deprecated the CHANGELOG.md file, from my point of view it could also be removed since previous releases are already existent (but not all from 0.1.0 release, so I only deprecate it). What do you think?
Please keep attention: for each new PR, it is important to set the correct label to correctly address the release note.
=> generate automatic release on tag

CHANGELOG.md, handler_test.go, opaevaluator.go, opamiddleware.go, opamiddleware_test.go, router_test.go
In this PR I add info logs at every policy evaluated complete with info about the policy, the path and the handler.
This bring to have 1 more line of log for every call if service is at info level. It can be ok to set this log at debug level, what do you think?
Maybe we could change it to debug when we expose some custom metrics
=> feat: add evaluation info logs

internal/metrics/metrics.go, internal/metrics/metrics_test.go
Testing in a real use case, sometimes specially with the filter policy the evaluation time is over 1s. So I think it's ok to add other higher buckets.
=> Add new bucket to metrics

internal/config/env_test.go, main_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
=> test: use `T.Setenv` to set env vars in tests

openapi/openapi_utils.go, openapi/openapi_utils_test.go
This fixes
```
[/github/workspace/openapi/openapi_utils.go:275] - G307 (CWE-703): Deferring unsafe method "Close" on type "io.ReadCloser" (Confidence: HIGH, Severity: MEDIUM)
274: 	}
> 275: 	defer resp.Body.Close()
276: 
```
Example job: https://github.com/rond-authz/rond/actions/runs/4144009188/jobs/7166550436#step:4:72
=> fix: sec warning for defer response body close

CHANGELOG.md, service/standalone_apis.go, service/standalone_apis_test.go
Right now when we create a binding and we pass permissions in the request body, they are ignored when the binding is created
=> fix: add permissions field to binding

core/opaevaluator.go, core/sdk_test.go, go.mod
[Allowed](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.53.1/rego#ResultSet.Allowed) documentation states:
>Allowed is a helper method that'll return true if all of these conditions hold: - the result set only has one element - there is only one expression in the result set's only element - that expression has the value `true` - there are no bindings.
>
>If bindings are present, this will yield `false`: it would be a pitfall to return `true` for a query like `data.authz.allow = x`, which always has result set element with value true, but could also have a binding `x: false`. 
Since the policy is actually returning the new body it is expected to return a single expression with value different from `true`
To verify:
Note:
The `verifyAllowed` function is supposed to be an internal …
=> fix(#210): allowed value log in response policy evaluation

core/input.go, main_test.go, mocks/rego-policies/example.rego, mocks/simplifiedMock.json, openapi/evaluators_test.go, openapi/openapi_utils_test.go, sdk/evaluator_test.go, sdk/rondinput/http/input.go, sdk/rondinput/http/input_test.go, sdk/sdk_test.go
This PR aims at closing #207; if this gets merged we could close #208
I've added unit tests on the SDK and input creator but also managed to add a specific integration test case to make sure it will properly be supported with the sidecar
=> feat(#207): add user id to input struct

.github/workflows/test.yml
I wanted to set requirements for PR to pass tests, however you are required to match the action job name, which previously included the golang version, therefore changing when updating golang.
With this PR I want to stabilize job names to be always consistent.
=> ci: new job names

core/errors.go, core/opaevaluator.go, core/partialevaluators_test.go, internal/fake/sdk.go, sdk/evaluator.go, sdk/evaluator_test.go, service/handler.go, service/router_test.go
Maybe, we could also returns the specific not allowed error. What do you think of this change?
=> feat: improve sdk request evaluator interface

core/opaevaluator.go, mocks/nestedPathsConfig.json, openapi/openapi_utils.go, openapi/openapi_utils_test.go, sdk/rondinput/http/input.go, sdk/rondinput/http/input_test.go, service/handler.go, service/opa_transport.go, service/opa_transport_test.go
This PR partially address #273; in the issue the proposal is to be able to decide on multiple levels when the body should not be read (request/response/all).
Working on the request side (which addresses our main issue) was easy, while working on the response is not immediately obvious, the problem there has two faces:
* there's still some tech debt on owns the responsibility to read the body
* the response flow is mostly meant to interact with the body, changing the underlying behaviour without proper considerations could make the feature useless
Having dealt with only the request flow I avoided working on the configuration at the general options level.
=> feat(#273): support for preventBodyLoad in request flow

Makefile, internal/fake/evaluatorFinder.go, main.go, main_test.go, service/opamiddleware.go, service/opamiddleware_test.go, service/router.go, service/router_test.go, service/sdkbootstate.go, service/sdkbootstate_test.go, service/statusroutes.go, service/statusroutes_test.go
This PR introduces changes to make status routes reply asap providing meaningful setup status, in particular:
- liveness: immediately OK, se service is alive since the web server is up!
- readiness: replies immediately, KO until SDK is ready, then returns OK
- check-up: acts as the liveness (do we still need this route? 🤔)
=> feat(#268): decouple status routes provisioning from policy setup

go.mod, go.sum, service/router.go
This PR fixes module issues due to https://github.com/ugorji/go/issues/299 and https://github.com/perimeterx/marshmallow using it
=> fix: go mod ambiguous imports

custom_builtins/mongoclient_test.go, internal/config/env.go, internal/config/env_test.go, internal/mongoclient/mongoclient.go, internal/mongoclient/mongoclient_test.go, main.go, sdk/inputuser/mongo/mongoclient_test.go
Added env var to control the MongoDB `maxIdleTimeMs` connection property
I decided to have a default value set to 1s to the var, we may consider further tuning in future patches if the value seems to aggressive. After some local benchmark I didn't found particular issues but my M2 processor is far too powerful compared to the general purpose GCP CPUs 😅
=> feat: mongodb maxIdleTimeMs

custom_builtins/mongoclient.go, sdk/inputuser/mongo/mongoclient.go, types/rbactypes.go
This PR fixes an issue with v1.12.0+ that exposes the NewMongoClient method (from `custom_builtins` and `mongoinputuser` packages) that uses the `internal/mongoclient` struct definition.
I've created a new interface (another one, gasp) that abstracts both clients. I've put it in the `types` package since is currently the only place that is shared among all the packages.
=> fix: prevent exposing interface using an internal package

.github/workflows/test.yml
Lot's of ci actions are failing due to a race with coveralls
```
/home/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_linux_amd64 -service=github -coverprofile=coverage.out
bad response status from coveralls: 422
{"message":"Can't add a job to a build that is already closed. Build 7255384918 is closed. See docs.coveralls.io/parallel-builds","error":true}
Error: Error: The process '/home/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_linux_amd64' failed with exit code 1
```
This pr should fix
=> fix: unstable ci due to coveralls race

.github/workflows/test.yml, sdk/evaluator_test.go
Update golang version to v1.22 for benchmark job
=> ci: go1.22 update for benchmark runs

core/input.go, core/input_test.go, core/opaevaluator.go, core/opaevaluator_test.go, core/partialevaluators.go, core/partialevaluators_test.go, core/rego.go, core/rego_test.go, sdk/evaluator.go
This PR will improve performance of query generation of more than x20, and it seems also the allow and response.
Here the before/after on my machine:
Before: 
```
BenchmarkEvaluateRequest-10                                 4534            255834 ns/op          194671 B/op       3024 allocs/op
BenchmarkEvaluateRequestWithQueryGeneration-10               154           7485473 ns/op         4507957 B/op     112217 allocs/op
BenchmarkEvaluateResponse-10                                1639            702470 ns/op          486613 B/op       7980 allocs/op
```
After:
```
BenchmarkEvaluateRequest-10                                 5054            208840 ns/op          165831 B/op       2437 allocs/op
BenchmarkEvaluateRequestWithQueryGeneration-10              3505            339451 ns/op …
```
=> perf: prepare partial evaluation at boot for better performances

go.mod, go.sum, integration_test.go
Small PR introducing an additional integration test with a concurrent load of 100_000 requests
=> test: add integration test with concurrent request load

internal/audit/agent.go, internal/audit/agent_log.go, internal/audit/agent_log_test.go, internal/audit/agent_test.go, internal/audit/cache.go, logging/test/logger.go, sdk/audit_factory.go, sdk/audit_factory_test.go, sdk/evaluator.go, sdk/evaluator_test.go, sdk/openapi.go, sdk/openapi_test.go, sdk/sdk.go
=> fix: resolve concurrent map writes for audit cache

internal/config/env.go, internal/config/env_test.go, main.go
configuration file read is based on env presence, whose default value has been removed
=> fix: make audit config file optional
